### ISSUE TITLE
Only allow (PhD) students to submit if supervisor is added

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#486] opened 2023-05-23 08:59 UTC
I recently received an application in which a (PhD) student had added himself as 'researcher with final responsibility'. This should not be possible.

**Comment by tymees** [comment] 2023-09-28 12:10
Duplicate of #531, which has more info. Thus, I'm closing this older one

**Closed by tymees** 2023-09-28 12:10 UTC
