### ISSUE TITLE
Dead link on Data Management page

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#633] opened 2024-03-22 12:26 UTC
This text is not applicable anymore (that workshop does not exist anymore):

_Recommended workshops
If you have not already done so, it is highly recommended you attend:

the workshop [Handling personal data in research](https://www.uu.nl/en/node/81799)_

Please replace with:

Recommended:
For all your questions regarding privacy, e.g.: "What are personal data?" or "When may I call my research anonymous?", consult the Data Privacy Handbook(https://utrechtuniversity.github.io/dataprivacyhandbook/).

**Comment by miggol** [comment] 2024-03-28 14:50
Closing as duplicate of #608

**Closed by miggol** 2024-03-28 14:50 UTC
