### ISSUE TITLE
Startpage - Before you begin out of sight

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#791] opened 2024-12-04 16:59 UTC
Not sure what can be done about this, but I totally missed the 'Before you begin' text. Not sure if this is dependent on your screen or something, but I think one should at least see that there is information to be read 'before you begin'.

I now see this only applies to the Dutch text....

**Comment by miggol** [comment] 2024-12-10 14:31
Duplicate of #812

**Closed by miggol** 2024-12-10 14:31 UTC
