### ISSUE TITLE
Data not saved or validated when clearing existing data

### ISSUE THREAD

**Issue by tijmenbaarda** [DH-IT-Portal-Development/ethics#732] opened 2024-10-23 15:02 UTC
In several forms, when a user clears data in a form that was already saved before, and then proceeds, the cleared form is not saved and a validation error is not given either. Instead, the old data remains in the database. However, the user proceeds to the next form as if the data has been saved.

In the worst case, it may happen that an application with old data is sent out, because the old data is still there and the system shows the step as complete.

This happens in the following forms (at least):
* Research goal
* Funding information (when deselecting all checkboxes)
* Other researchers (only the field "Name and affiliation of other people")
In the form "Researcher", this does not happen and the emptied fields are correctly validated.

**Comment by miggol** [comment] 2024-10-25 11:28
Thanks for mentioning! I think this is a duplicate of #126 

Sadly we don't really have a way forward to fixing this short of a massive overhaul. Won't be fixed for this big update :(

**Closed by miggol** 2024-10-25 11:28 UTC
Labels: bug
